config/routes.rb
Famlog::Application.routes.draw do |map|

  root       :to => 'home#index'
  devise_for :users, :controllers => { :sessions => 'sessions' }

  resources  :events
  resources  :messages do
    resources :replies
  end

  resource :family do
    resources :members
  end

  match '/help' => 'home#help', :as => :help
  match ':controller(/:action(/:id(.:format)))'

end

app/controllers/events_controller.rb
require 'famlog/datetime_parser'

class EventsController < MessagesControllerBase
  before_filter :find_message_and_verify_ownership, :except => [:new, :create]

  private

  def before_save(params)
    @message.start_at = Famlog::DateTimeParser.parse(params[:s_date], params[:s_time])
    @message.end_at   = Famlog::DateTimeParser.parse(params[:e_date], params[:e_time])

    @message.is_event = true
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def time_opts
    t = []
    format = lambda { |x| x.strftime('%l:%M %P').strip }
    24.times do |i|
      t << format.call(Time.local(1999, 9, 9, i, 00))
      t << format.call(Time.local(1999, 9, 9, i, 30))
    end
    t
  end
end

app/views/events/_form.html.haml
%p
  = f.label :title
  = f.text_field :title
%p
  = f.label :message
  = f.text_area :text
%p
  = f.label :importance
  = f.select :importance, Importance::ALL

%p
  = f.label :start_at
  .date-group
    = text_field_tag :s_date, @message.start_date_display, :class => 'date'
    \-
    = select_tag :s_time, options_for_select(time_opts, @message.start_time_display), :class => 'time'

%p
  = f.label :end_date
  .date-group
    = text_field_tag :e_date, @message.end_date_display, :class => 'date'
    \-
    = select_tag :e_time, options_for_select(time_opts, @message.end_time_display), :class => 'time'

%p
  = f.submit "Submit", :class => "submit"
  or
  = link_to "Cancel", root_path, :class => "cancel"

app/views/events/edit.html.haml
- content_for :head do
  = stylesheet_link_tag "forms"
%h2 Edit Event
- form_for @message, :url => event_path(@message) do |f|
  = render :partial => "form", :locals => { :f => f }

app/views/events/new.html.haml
= content_for :head do
  = stylesheet_link_tag "forms"
%h2 New Event
= form_for @message, :url => events_path do |f|
  = render :partial => "form", :locals => { :f => f }