config/routes.rb
Famlog::Application.routes.draw do |map|

  root       :to => 'home#index'
  devise_for :users, :controllers => { :sessions => 'sessions' }

  resources  :events
  resources  :messages do
    resources :replies
  end

  resource :family do
    resources :members
  end

  match '/help' => 'home#help', :as => :help
  match ':controller(/:action(/:id(.:format)))'

end

app/views/layouts/_header.html.haml
#header-clip
  #header
    #hdr-group
      %h1
        = link_to 'famlog', root_path
      %ul#hdr-util
        - if current_user
          %li
            = link_to current_user.username.capitalize, edit_user_registration_path(current_user.username)
          %li
            = link_to 'Family', family_path
          %li
            = link_to 'Help', help_path
          %li
            = link_to 'Sign out', destroy_user_session_path
        - else
          %li
            = link_to 'Sign in', new_user_session_path
          %li
            |
          %li
            = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Famlog
    = stylesheet_link_tag 'reset', 'common'
    = csrf_meta_tag
    = yield :head
  %body
    = render :partial => 'layouts/header'
    #root
      #top
        = today
        #add
          Create a new
          = link_to 'Message', new_message_path
          or
          = link_to 'Event', new_event_path
        #tabs
          %ul
            %li#home.active
              Home
            %li#today
              = today_label
            %li#forecast
              = forecast_label
            %li#history
              History
            %li#search
              Search
      #main
        = yield

    = javascript_include_tag 'jquery', 'rails',
                             'application', 'messages', 'tabs'

app/views/layouts/modal.html.haml
!!!
%html
  %head
    %title Famlog
    = stylesheet_link_tag "reset", "common", "forms", "modal"
    = csrf_meta_tag
  %body
    %h1 famlog
    #root
      #main
        = yield

app/views/layouts/no_tabs.html.haml
!!!
%html
  %head
    %title Famlog
    = stylesheet_link_tag 'reset', 'common', 'forms', 'jquery-ui'
    = csrf_meta_tag
    = yield :head
  %body
    = render :partial => 'layouts/header'
    #root
      #main
        = yield

    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js',
                             'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js',
                             'rails', 'forms'

app/views/layouts/post.html.haml
!!!
%html
  %head
    %title famlog
    = stylesheet_link_tag 'reset', 'common', 'forms'
    = csrf_meta_tag
    = yield :head
  %body
    = render :partial => 'layouts/header'
    #root
      #main
        = yield

    = javascript_include_tag 'jquery.js', 'rails'